// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnoEmrxoVojn0uRVMNLdqBUC0sCRCGlKs',
    appId: '1:1017415678363:web:1c5cf6616b66740a52893e',
    messagingSenderId: '1017415678363',
    projectId: 'spacemall-v1',
    authDomain: 'spacemall-v1.firebaseapp.com',
    storageBucket: 'spacemall-v1.appspot.com',
    measurementId: 'G-1T7TCNDGLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwHhpISVlHImqzxXaJZ5wWZFfL2L-gTis',
    appId: '1:1017415678363:android:89ca0d90a17a1f9052893e',
    messagingSenderId: '1017415678363',
    projectId: 'spacemall-v1',
    storageBucket: 'spacemall-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCltCUmBltGB_dh5HZcBm_Ag-adBm06HRE',
    appId: '1:1017415678363:ios:56a87228cd7415be52893e',
    messagingSenderId: '1017415678363',
    projectId: 'spacemall-v1',
    storageBucket: 'spacemall-v1.appspot.com',
    androidClientId: '1017415678363-1mbva1dvqeopov2rtoe0ib92ohp6l91c.apps.googleusercontent.com',
    iosClientId: '1017415678363-mlb586r2fladi8jjmnmeamefpstcnrvg.apps.googleusercontent.com',
    iosBundleId: 'io.spacemall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCltCUmBltGB_dh5HZcBm_Ag-adBm06HRE',
    appId: '1:1017415678363:ios:56a87228cd7415be52893e',
    messagingSenderId: '1017415678363',
    projectId: 'spacemall-v1',
    storageBucket: 'spacemall-v1.appspot.com',
    androidClientId: '1017415678363-1mbva1dvqeopov2rtoe0ib92ohp6l91c.apps.googleusercontent.com',
    iosClientId: '1017415678363-mlb586r2fladi8jjmnmeamefpstcnrvg.apps.googleusercontent.com',
    iosBundleId: 'io.spacemall',
  );
}
